//! Manual probe for observing how the Codex CLI's TUI and the Codex App
//! Server react when a `item/commandExecution/requestApproval` request is
//! answered by something other than the real CLI.
//!
//! This mirrors `claude_hook_probe.rs` in spirit (CLI argument handling, log
//! formatting, and process-lifecycle conventions) but targets the Codex
//! Broker's WebSocket JSON-RPC relay (`crates/rawhid-host-core/src/codex_broker.rs`)
//! instead of Claude Code's HTTP hooks.
//!
//! Topology:
//!
//! ```text
//! [Codex CLI]  --WS-->  [this probe: intercepting relay]  --WS-->  [codex app-server]
//!    started by a human in a separate terminal      spawned by this program
//! ```
//!
//! The probe spawns `codex app-server`, listens for the CLI's WebSocket
//! connection itself (printing a copy-pasteable launch command for a human
//! to run in another terminal — the CLI is a TUI and must never be started
//! by this probe), and relays every frame between the two sides while
//! logging it in full. When it detects a `requestApproval` request flowing
//! from the App Server to the CLI, it can additionally answer that request
//! itself (impersonating the CLI), either alongside the CLI's real answer
//! (`race`, answering question Q-A: does a duplicate response confuse
//! anything?) or instead of forwarding the request to the CLI at all
//! (`hold`, answering question Q-B: can the Broker resolve approvals without
//! the CLI ever seeing them?). `hold-forever` withholds the request and
//! never answers it, to probe the App Server's own timeout behavior.
//!
//! Response shape and `availableDecisions` were confirmed against the actual
//! schema generated by `codex app-server generate-json-schema --experimental`
//! (see `CommandExecutionRequestApprovalResponse.json` /
//! `CommandExecutionRequestApprovalParams.json`), not assumed from design
//! docs. The response is exactly `{"decision": <one element of
//! availableDecisions, treated as opaque JSON>}`.

use std::{
    collections::HashMap,
    env,
    ffi::OsString,
    fs::{self, File, OpenOptions},
    io::Write as _,
    net::SocketAddr,
    path::{Path, PathBuf},
    process::{ExitCode, Stdio},
    sync::{
        atomic::{AtomicBool, AtomicUsize, Ordering},
        Arc, Mutex as StdMutex,
    },
    time::{Duration, Instant},
};

use chrono::Local;
use futures_util::{SinkExt, StreamExt};
use rawhid_host_core::codex_broker::{
    classify_json_rpc, JsonRpcKind, JsonRpcMetadata, SUPPORTED_CODEX_VERSION,
    SUPPORTED_SCHEMA_SHA256,
};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use subtle::ConstantTimeEq;
use tokio::{
    net::{TcpListener, TcpStream},
    process::{Child, Command},
    sync::{mpsc, watch},
    time,
};
use tokio_tungstenite::{
    accept_hdr_async, connect_async,
    tungstenite::{
        client::IntoClientRequest,
        handshake::server::{Request, Response},
        http::StatusCode,
        Message,
    },
    WebSocketStream,
};

const REQUEST_APPROVAL_METHOD: &str = "item/commandExecution/requestApproval";
const PROBE_TOKEN_ENV: &str = "KEYLINK_CODEX_APPROVAL_PROBE_TOKEN";
const CLI_TO_APP: &str = "cli->app";
const APP_TO_CLI: &str = "app->cli";
const PROBE_TO_APP: &str = "probe->app";
const APP_SERVER_STARTUP_TIMEOUT: Duration = Duration::from_secs(20);
const UPSTREAM_CONNECT_TIMEOUT: Duration = Duration::from_secs(10);
const SHUTDOWN_TIMEOUT: Duration = Duration::from_secs(5);
const WRITER_DRAIN_TIMEOUT: Duration = Duration::from_secs(3);
/// How long an occurrence must stay "responded + turn/completed" before it
/// is considered settled. See `schedule_settlement_watch` for why this
/// exists instead of a fixed post-detection timer.
const SETTLE_TAIL: Duration = Duration::from_secs(3);
const SETTLE_POLL_INTERVAL: Duration = Duration::from_millis(200);
const DEFAULT_OBSERVE_SECONDS: u64 = 120;

fn main() -> ExitCode {
    let args: Vec<OsString> = env::args_os().skip(1).collect();
    if args.iter().any(|arg| arg == "--help" || arg == "-h") {
        print_usage();
        return ExitCode::SUCCESS;
    }
    let options = match parse_args(&args) {
        Ok(options) => options,
        Err(error) => {
            eprintln!("{error}");
            print_usage();
            return ExitCode::from(2);
        }
    };

    let runtime = match tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
    {
        Ok(runtime) => runtime,
        Err(error) => {
            eprintln!("failed to create runtime: {error}");
            return ExitCode::FAILURE;
        }
    };
    match runtime.block_on(run(options)) {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("codex_approval_probe failed: {error}");
            ExitCode::FAILURE
        }
    }
}

fn print_usage() {
    eprintln!(
        "Usage:\n  codex_approval_probe --mode <observe|race|hold|hold-forever> [options]\n\n\
         Modes:\n\
         \x20 observe       forward every frame untouched (baseline)\n\
         \x20 race          forward requestApproval to the CLI AND also answer it from the\n\
         \x20                probe after --delay-seconds (Q-A: does a duplicate answer break\n\
         \x20                anything?)\n\
         \x20 hold          withhold requestApproval from the CLI; the probe answers it after\n\
         \x20                --delay-seconds (Q-B: can the Broker resolve it without the CLI?)\n\
         \x20 hold-forever  withhold requestApproval and never answer it (App Server timeout?)\n\n\
         Options:\n\
         \x20 --delay-seconds <n>       default 5\n\
         \x20 --observe-seconds <n>     default 120; how long to keep observing ONE\n\
         \x20                            requestApproval occurrence, at most, waiting for it to\n\
         \x20                            settle (see below) before giving up on it\n\
         \x20 --decision <value>        default: availableDecisions[0]\n\
         \x20 --codex <path>            default: resolved from PATH, like codex_broker.rs does\n\
         \x20 --out-dir <path>          default: a fresh directory under the system temp dir\n\
         \x20 --app-server-port <port>  default 0 (auto)\n\
         \x20 --proxy-port <port>       default 0 (auto)\n\
         \x20 --max-approvals <n>       default 1; auto-exit once N occurrences have settled\n\n\
         An occurrence is 'processed' (counts toward --max-approvals) when EITHER: (a) it\n\
         settles -- a response (the probe's own or the CLI's) was observed, turn/completed\n\
         followed, and 3 more seconds passed with nothing else happening -- OR (b) \n\
         --observe-seconds elapses since it was first detected, whichever comes first. This is\n\
         NOT a fixed --delay-seconds timer: what hold/race need to observe is what happens\n\
         AFTER the probe intervenes (serverRequest/resolved, the command actually running,\n\
         turn/completed, a late/duplicate CLI response), which can take much longer than the\n\
         answer delay itself."
    );
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Mode {
    Observe,
    Race,
    Hold,
    HoldForever,
}

impl Mode {
    fn parse(value: &str) -> Result<Self, String> {
        match value {
            "observe" => Ok(Mode::Observe),
            "race" => Ok(Mode::Race),
            "hold" => Ok(Mode::Hold),
            "hold-forever" => Ok(Mode::HoldForever),
            other => Err(format!(
                "unknown --mode value: {other} (expected observe|race|hold|hold-forever)"
            )),
        }
    }
}

struct ProbeOptions {
    mode: Mode,
    delay: Duration,
    observe_seconds: Duration,
    decision: Option<String>,
    /// `None` means "resolve automatically from PATH", mirroring
    /// `codex_broker::resolve_codex_executable(None, ..)`.
    codex: Option<PathBuf>,
    out_dir: Option<PathBuf>,
    app_server_port: u16,
    proxy_port: u16,
    max_approvals: usize,
}

fn parse_args(args: &[OsString]) -> Result<ProbeOptions, String> {
    let mut mode = None;
    let mut delay_seconds: u64 = 5;
    let mut observe_seconds: u64 = DEFAULT_OBSERVE_SECONDS;
    let mut decision = None;
    let mut codex: Option<PathBuf> = None;
    let mut out_dir = None;
    let mut app_server_port: u16 = 0;
    let mut proxy_port: u16 = 0;
    let mut max_approvals: usize = 1;
    let mut index = 0;

    while index < args.len() {
        let flag = args[index].to_string_lossy();
        match flag.as_ref() {
            "--mode" => mode = Some(Mode::parse(&next_value(args, &mut index, "--mode")?)?),
            "--delay-seconds" => {
                delay_seconds = next_value(args, &mut index, "--delay-seconds")?
                    .parse::<u64>()
                    .map_err(|_| "--delay-seconds must be a non-negative integer".to_string())?;
            }
            "--observe-seconds" => {
                observe_seconds = next_value(args, &mut index, "--observe-seconds")?
                    .parse::<u64>()
                    .map_err(|_| "--observe-seconds must be a non-negative integer".to_string())?;
            }
            "--decision" => decision = Some(next_value(args, &mut index, "--decision")?),
            "--codex" => codex = Some(PathBuf::from(next_value(args, &mut index, "--codex")?)),
            "--out-dir" => {
                out_dir = Some(PathBuf::from(next_value(args, &mut index, "--out-dir")?))
            }
            "--app-server-port" => {
                app_server_port = next_value(args, &mut index, "--app-server-port")?
                    .parse::<u16>()
                    .map_err(|_| "--app-server-port must be 0-65535".to_string())?;
            }
            "--proxy-port" => {
                proxy_port = next_value(args, &mut index, "--proxy-port")?
                    .parse::<u16>()
                    .map_err(|_| "--proxy-port must be 0-65535".to_string())?;
            }
            "--max-approvals" => {
                max_approvals = next_value(args, &mut index, "--max-approvals")?
                    .parse::<usize>()
                    .map_err(|_| "--max-approvals must be a positive integer".to_string())?;
                if max_approvals == 0 {
                    return Err("--max-approvals must be greater than zero".to_string());
                }
            }
            other => return Err(format!("unknown option: {other}")),
        }
        index += 1;
    }

    let mode =
        mode.ok_or_else(|| "--mode is required (observe|race|hold|hold-forever)".to_string())?;
    Ok(ProbeOptions {
        mode,
        delay: Duration::from_secs(delay_seconds),
        observe_seconds: Duration::from_secs(observe_seconds),
        decision,
        codex,
        out_dir,
        app_server_port,
        proxy_port,
        max_approvals,
    })
}

fn next_value(args: &[OsString], index: &mut usize, flag: &str) -> Result<String, String> {
    *index += 1;
    args.get(*index)
        .map(|value| value.to_string_lossy().into_owned())
        .ok_or_else(|| format!("{flag} requires a value"))
}

/// Everything a frame handler or a delayed-response task needs. Cheap to
/// clone (every field is an `Arc`, a `Copy` type, or small owned data).
#[derive(Clone)]
struct SharedState {
    logger: Arc<Logger>,
    tracked: Arc<StdMutex<HashMap<String, TrackedApproval>>>,
    /// Every requestApproval frame seen, counted the instant it is detected.
    /// Only used to number the "#N/max detected" log line -- it does NOT
    /// drive shutdown (see `approvals_processed`).
    approvals_detected: Arc<AtomicUsize>,
    /// Occurrences that have finished being observed, one way or another
    /// (settled, or timed out -- see `schedule_settlement_watch`). Reaching
    /// `max_approvals` here is what actually ends the run.
    approvals_processed: Arc<AtomicUsize>,
    /// Set once the final shutdown has been triggered and logged, so a race
    /// between Ctrl+C and the last occurrence settling logs exactly one
    /// "shutdown reason" line instead of two.
    final_shutdown_triggered: Arc<AtomicBool>,
    /// Set when the run's terminating trigger was an observe-window timeout
    /// (outcome (b)), so the summary can carry the "aftermath may be
    /// incomplete" warning.
    final_shutdown_is_timeout: Arc<AtomicBool>,
    max_approvals: usize,
    delay: Duration,
    observe_seconds: Duration,
    decision_arg: Option<String>,
    mode: Mode,
    shutdown_tx: watch::Sender<bool>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum SettlementOutcome {
    Settled,
    TimedOut,
}

struct TrackedApproval {
    id: Value,
    turn_id: Option<String>,
    detected_at_ms: u128,
    decision: Option<Value>,
    note: String,
    probe_response_sent: bool,
    probe_response_at_ms: Option<u128>,
    cli_response_seen: bool,
    cli_response_at_ms: Option<u128>,
    /// The `result` (or `error`) object of the CLI's own response, if one
    /// was observed -- this is the "what did it contain" half of the
    /// duplicate-response question for `race` mode.
    cli_response_body: Option<Value>,
    turn_completed: bool,
    turn_completed_at_ms: Option<u128>,
    turn_status: Option<String>,
    resolved_notification_seen: bool,
    resolved_notification_at_ms: Option<u128>,
    error_response_seen: bool,
    error_response_at_ms: Option<u128>,
    /// How this occurrence's observation window ended; `None` until
    /// `schedule_settlement_watch`'s task finalizes it.
    outcome: Option<SettlementOutcome>,
    outcome_at_ms: Option<u128>,
}

impl TrackedApproval {
    fn new(id: Value, turn_id: Option<String>, detected_at_ms: u128) -> Self {
        Self {
            id,
            turn_id,
            detected_at_ms,
            decision: None,
            note: String::new(),
            probe_response_sent: false,
            probe_response_at_ms: None,
            cli_response_seen: false,
            cli_response_at_ms: None,
            cli_response_body: None,
            turn_completed: false,
            turn_completed_at_ms: None,
            turn_status: None,
            resolved_notification_seen: false,
            resolved_notification_at_ms: None,
            error_response_seen: false,
            error_response_at_ms: None,
            outcome: None,
            outcome_at_ms: None,
        }
    }
}

async fn run(options: ProbeOptions) -> Result<(), String> {
    let run_stamp = Local::now().format("%Y%m%d-%H%M%S").to_string();
    let out_dir = match &options.out_dir {
        Some(dir) => dir.clone(),
        None => env::temp_dir().join(format!(
            "codex-approval-probe-{run_stamp}-{}",
            std::process::id()
        )),
    };
    let out_dir = absolute_path(&out_dir)?;
    fs::create_dir_all(&out_dir)
        .map_err(|error| format!("failed to create out-dir {}: {error}", out_dir.display()))?;

    let log_path = out_dir.join(format!("codex-approval-probe-{run_stamp}.log"));
    let logger = Arc::new(Logger::create(&log_path)?);
    logger.line(&format!("log file: {}", log_path.display()));
    logger.line(&format!(
        "mode={:?} delay={:?} observe_seconds={:?} decision_arg={:?} max_approvals={} \
         codex_requested={} out_dir={} app_server_port_requested={} proxy_port_requested={}",
        options.mode,
        options.delay,
        options.observe_seconds,
        options.decision,
        options.max_approvals,
        options
            .codex
            .as_deref()
            .map(|path| path.display().to_string())
            .unwrap_or_else(|| "<auto: resolved from PATH>".to_string()),
        out_dir.display(),
        options.app_server_port,
        options.proxy_port
    ));

    let codex = resolve_codex_executable(options.codex.as_deref()).await?;
    logger.line(&format!("codex executable: {}", codex.display()));

    let codex_version = probe_codex_version(&codex, &logger).await?;
    logger.line(&format!("codex --version -> {codex_version}"));
    if codex_version != SUPPORTED_CODEX_VERSION {
        logger.line(&format!(
            "NOTE: detected version differs from the Broker's SUPPORTED_CODEX_VERSION \
             ({SUPPORTED_CODEX_VERSION}); this probe does not enforce compatibility, proceeding anyway"
        ));
    }

    generate_and_log_schema(&codex, &out_dir, &logger).await?;

    let app_server_token = random_token()?;
    let cli_token = random_token()?;
    let app_server_token_path = out_dir.join("app-server.token");
    let cli_token_path = out_dir.join("cli.token");
    fs::write(&app_server_token_path, &app_server_token)
        .map_err(|error| format!("failed to write App Server token file: {error}"))?;
    fs::write(&cli_token_path, &cli_token)
        .map_err(|error| format!("failed to write CLI token file: {error}"))?;

    let app_server_port = if options.app_server_port == 0 {
        pick_free_port().await?
    } else {
        options.app_server_port
    };
    let app_server_url = format!("ws://127.0.0.1:{app_server_port}");

    let mut command = Command::new(&codex);
    command
        .arg("app-server")
        .arg("--listen")
        .arg(&app_server_url)
        .arg("--ws-auth")
        .arg("capability-token")
        .arg("--ws-token-file")
        .arg(&app_server_token_path)
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::null());
    hide_child_window(&mut command);
    logger.line(&format!(
        "spawning: {} app-server --listen {app_server_url} --ws-auth capability-token \
         --ws-token-file {}",
        codex.display(),
        app_server_token_path.display()
    ));
    let mut child = command
        .spawn()
        .map_err(|error| format!("failed to spawn Codex App Server: {error}"))?;
    let child_stdin = child.stdin.take();
    let mut guard = ChildKillGuard::new(child);

    wait_for_port(
        guard.as_mut(),
        app_server_port,
        APP_SERVER_STARTUP_TIMEOUT,
        &logger,
    )
    .await?;

    let listener = TcpListener::bind(("127.0.0.1", options.proxy_port))
        .await
        .map_err(|error| {
            format!(
                "failed to bind proxy listener on 127.0.0.1:{}: {error}",
                options.proxy_port
            )
        })?;
    let proxy_port = listener
        .local_addr()
        .map_err(|error| format!("failed to read proxy listener address: {error}"))?
        .port();
    logger.line(&format!("proxy listening on 127.0.0.1:{proxy_port}"));

    print_launch_instructions(&logger, &cli_token_path, proxy_port);

    let (shutdown_tx, mut shutdown_rx) = watch::channel(false);
    ctrlc::install();

    let state = SharedState {
        logger: logger.clone(),
        tracked: Arc::new(StdMutex::new(HashMap::new())),
        approvals_detected: Arc::new(AtomicUsize::new(0)),
        approvals_processed: Arc::new(AtomicUsize::new(0)),
        final_shutdown_triggered: Arc::new(AtomicBool::new(false)),
        final_shutdown_is_timeout: Arc::new(AtomicBool::new(false)),
        max_approvals: options.max_approvals,
        delay: options.delay,
        observe_seconds: options.observe_seconds,
        decision_arg: options.decision.clone(),
        mode: options.mode,
        shutdown_tx: shutdown_tx.clone(),
    };

    {
        let state = state.clone();
        tokio::spawn(async move {
            loop {
                if ctrlc::SHUTDOWN_REQUESTED.load(Ordering::SeqCst) {
                    if !state.final_shutdown_triggered.swap(true, Ordering::SeqCst) {
                        state.logger.line("shutdown reason: ctrl-c");
                    }
                    let _ = state.shutdown_tx.send(true);
                    break;
                }
                time::sleep(Duration::from_millis(100)).await;
            }
        });
    }

    loop {
        if *shutdown_rx.borrow() {
            break;
        }
        tokio::select! {
            changed = shutdown_rx.changed() => {
                if changed.is_err() || *shutdown_rx.borrow() {
                    break;
                }
            }
            accepted = listener.accept() => {
                let (stream, peer) = match accepted {
                    Ok(pair) => pair,
                    Err(error) => {
                        logger.line(&format!("ERROR accept failed: {error}"));
                        continue;
                    }
                };
                logger.line(&format!("TCP connection from {peer}"));
                match accept_downstream(stream, &cli_token).await {
                    Ok(downstream) => {
                        logger.line(&format!("CLI connected from {peer} (authorized)"));
                        match connect_upstream(&app_server_url, &app_server_token).await {
                            Ok(upstream) => {
                                logger.line("connected to Codex App Server upstream");
                                let reason = bridge_session(downstream, upstream, state.clone()).await;
                                logger.line(&format!("bridge session ended: {reason}"));
                            }
                            Err(error) => {
                                logger.line(&format!("ERROR upstream connect failed: {error}"));
                            }
                        }
                    }
                    Err(error) => {
                        logger.line(&format!("WARN downstream handshake rejected: {error}"));
                    }
                }
            }
        }
    }

    logger.line("shutting down: terminating Codex App Server child process");
    drop(child_stdin);
    let mut child = guard.into_inner();
    match time::timeout(SHUTDOWN_TIMEOUT, child.wait()).await {
        Ok(Ok(status)) => logger.line(&format!("Codex App Server exited: {status}")),
        Ok(Err(error)) => logger.line(&format!(
            "WARN failed to wait for Codex App Server: {error}"
        )),
        Err(_) => {
            logger.line("WARN Codex App Server did not exit in time; killing");
            let _ = child.start_kill();
            let _ = child.wait().await;
        }
    }

    let timed_out = state.final_shutdown_is_timeout.load(Ordering::SeqCst);
    print_summary(&logger, &state.tracked, timed_out);
    Ok(())
}

/// Resolves the Codex executable exactly like
/// `codex_broker::resolve_codex_executable` does, for the same reason: on
/// this machine `codex` is an npm shim (`codex.cmd`, no `codex.exe`
/// anywhere on PATH). `std`/`tokio`'s `Command::new("codex")` only resolves
/// a bare program name against `.exe` on Windows -- it does NOT consult
/// `PATHEXT`, so it never finds `.cmd`/`.bat` shims. Passing `Command::new`
/// a bare `"codex"` is exactly what broke the first real run of this probe
/// (`failed to run \`codex --version\`: program not found`) even though a
/// normal shell, and `where.exe codex`, find it immediately. Resolving the
/// executable ourselves via `where.exe`/`which` and always spawning the
/// fully-qualified path avoids that hole -- do not go back to
/// `Command::new(&options.codex)` with an unresolved bare name.
async fn resolve_codex_executable(configured: Option<&Path>) -> Result<PathBuf, String> {
    if let Some(path) = configured {
        if !path.is_absolute() {
            return Err(format!(
                "--codex must be an absolute path to the Codex executable (relative paths are \
                 not resolved against PATH); got {}",
                path.display()
            ));
        }
        if !path.is_file() {
            return Err(format!(
                "--codex points at a path that is not an existing file: {}",
                path.display()
            ));
        }
        return fs::canonicalize(path).map_err(|error| {
            format!(
                "failed to canonicalize --codex path {}: {error}",
                path.display()
            )
        });
    }

    let (program, args): (&str, &[&str]) = if cfg!(windows) {
        ("where.exe", &["codex"])
    } else {
        ("which", &["codex"])
    };
    let output = Command::new(program)
        .args(args)
        .output()
        .await
        .map_err(|error| {
            format!(
                "failed to run `{program} {}` to locate the Codex executable: {error}",
                args[0]
            )
        })?;
    if !output.status.success() {
        return Err(format!(
            "codex was not found on PATH (searched with `{program} {}`); pass --codex <path> \
             with an explicit, absolute path to the Codex executable",
            args[0]
        ));
    }
    let path = select_codex_executable(&output.stdout).ok_or_else(|| {
        format!(
            "`{program} {}` printed candidates but none had a runnable extension \
             (.com/.exe/.bat/.cmd): {:?}",
            args[0],
            String::from_utf8_lossy(&output.stdout).trim()
        )
    })?;
    fs::canonicalize(&path).map_err(|error| {
        format!(
            "failed to canonicalize resolved Codex executable {}: {error}",
            path.display()
        )
    })
}

/// Picks the first `where.exe codex` / `which codex` output line that has a
/// runnable extension. `where.exe` can print several candidates -- on this
/// machine, an extensionless `codex` shell script line ahead of the actual
/// `codex.cmd` shim -- and the extensionless one is not something
/// `Command::new` can execute directly on Windows, so it must be skipped
/// rather than picked first.
fn select_codex_executable(output: &[u8]) -> Option<PathBuf> {
    String::from_utf8_lossy(output)
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .map(PathBuf::from)
        .find(|path| {
            if !cfg!(windows) {
                return true;
            }
            path.extension().is_some_and(|extension| {
                matches!(
                    extension.to_string_lossy().to_ascii_lowercase().as_str(),
                    "com" | "exe" | "bat" | "cmd"
                )
            })
        })
}

async fn probe_codex_version(codex: &Path, logger: &Logger) -> Result<String, String> {
    let output = Command::new(codex)
        .arg("--version")
        .output()
        .await
        .map_err(|error| format!("failed to run `{} --version`: {error}", codex.display()))?;
    if !output.status.success() {
        return Err(format!(
            "`{} --version` failed: {}",
            codex.display(),
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let _ = logger;
    Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

async fn generate_and_log_schema(
    codex: &Path,
    out_dir: &Path,
    logger: &Logger,
) -> Result<(), String> {
    let schema_dir = out_dir.join("schema");
    fs::create_dir_all(&schema_dir)
        .map_err(|error| format!("failed to create schema dir: {error}"))?;
    let output = Command::new(codex)
        .arg("app-server")
        .arg("generate-json-schema")
        .arg("--experimental")
        .arg("--out")
        .arg(&schema_dir)
        .output()
        .await
        .map_err(|error| format!("failed to run generate-json-schema: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "generate-json-schema failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let schema_path = schema_dir.join("codex_app_server_protocol.schemas.json");
    let schema_bytes = fs::read(&schema_path)
        .map_err(|error| format!("failed to read {}: {error}", schema_path.display()))?;
    let schema_sha256 = hex::encode_upper(Sha256::digest(&schema_bytes));
    logger.line(&format!(
        "generated schema SHA-256={schema_sha256} (Broker's SUPPORTED_SCHEMA_SHA256={SUPPORTED_SCHEMA_SHA256}, match={})",
        schema_sha256 == SUPPORTED_SCHEMA_SHA256
    ));

    let response_schema_path = schema_dir.join("CommandExecutionRequestApprovalResponse.json");
    if let Ok(text) = fs::read_to_string(&response_schema_path) {
        logger.block(
            "confirmed requestApproval response schema (CommandExecutionRequestApprovalResponse.json)",
            &text,
        );
    } else {
        logger.line("WARN CommandExecutionRequestApprovalResponse.json was not found in the generated schema");
    }
    let params_schema_path = schema_dir.join("CommandExecutionRequestApprovalParams.json");
    if let Ok(text) = fs::read_to_string(&params_schema_path) {
        logger.block(
            "confirmed requestApproval params schema (CommandExecutionRequestApprovalParams.json)",
            &text,
        );
    }
    Ok(())
}

fn print_launch_instructions(logger: &Logger, cli_token_path: &Path, proxy_port: u16) {
    logger.raw("");
    logger.raw("================ RUN THIS IN A SEPARATE TERMINAL (PowerShell) ================");
    logger.raw(&format!(
        "$env:{PROBE_TOKEN_ENV} = (Get-Content -LiteralPath {} -Raw).Trim()",
        powershell_quote(&cli_token_path.display().to_string())
    ));
    logger.raw(&format!(
        "codex --remote {} --remote-auth-token-env {PROBE_TOKEN_ENV}",
        powershell_quote(&format!("ws://127.0.0.1:{proxy_port}"))
    ));
    logger.raw("================================================================================");
    logger.raw("");
    logger.raw("Do NOT run this command yourself; a human runs it in a separate terminal. The");
    logger.raw("Codex CLI is a TUI and this probe must not launch it.");
    logger.raw("");
}

fn powershell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

async fn accept_downstream(
    stream: TcpStream,
    cli_token: &str,
) -> Result<WebSocketStream<TcpStream>, String> {
    let cli_token = cli_token.to_string();
    // tungstenite's `Callback` trait dictates this exact `Result<Response,
    // ErrorResponse>` signature; `ErrorResponse` (`http::Response<Option<String>>`)
    // is not something this closure can shrink or box.
    #[allow(clippy::result_large_err)]
    let callback = move |request: &Request, response: Response| {
        let authorized = request
            .headers()
            .get("authorization")
            .and_then(|value| value.to_str().ok())
            .and_then(|value| value.strip_prefix("Bearer "))
            .map(|token| constant_time_eq(token, &cli_token))
            .unwrap_or(false);
        if authorized {
            Ok(response)
        } else {
            let error_response = tokio_tungstenite::tungstenite::http::Response::builder()
                .status(StatusCode::UNAUTHORIZED)
                .body(Some("Unauthorized".to_string()))
                .expect("static 401 response is well-formed");
            Err(error_response)
        }
    };
    accept_hdr_async(stream, callback)
        .await
        .map_err(|error| error.to_string())
}

async fn connect_upstream(
    app_server_url: &str,
    app_server_token: &str,
) -> Result<WebSocketStream<tokio_tungstenite::MaybeTlsStream<TcpStream>>, String> {
    let mut upstream_request = app_server_url
        .into_client_request()
        .map_err(|error| format!("failed to build upstream request: {error}"))?;
    let header_value = format!("Bearer {app_server_token}")
        .parse()
        .map_err(|error| format!("invalid App Server authorization header: {error}"))?;
    upstream_request
        .headers_mut()
        .insert("authorization", header_value);
    match time::timeout(UPSTREAM_CONNECT_TIMEOUT, connect_async(upstream_request)).await {
        Ok(Ok((socket, _response))) => Ok(socket),
        Ok(Err(error)) => Err(error.to_string()),
        Err(_) => Err("timed out".to_string()),
    }
}

async fn bridge_session<Upstream>(
    downstream: WebSocketStream<TcpStream>,
    upstream: WebSocketStream<Upstream>,
    state: SharedState,
) -> &'static str
where
    Upstream: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin + Send + 'static,
{
    let (mut downstream_write, mut downstream_read) = downstream.split();
    let (upstream_write, mut upstream_read) = upstream.split();

    let (upstream_tx, mut upstream_rx) = mpsc::unbounded_channel::<Message>();
    let mut writer_task = tokio::spawn(async move {
        let mut upstream_write = upstream_write;
        while let Some(message) = upstream_rx.recv().await {
            if upstream_write.send(message).await.is_err() {
                break;
            }
        }
    });

    let mut shutdown_rx = state.shutdown_tx.subscribe();
    let reason: &'static str = loop {
        tokio::select! {
            changed = shutdown_rx.changed() => {
                if changed.is_err() || *shutdown_rx.borrow() {
                    let _ = upstream_tx.send(Message::Close(None));
                    let _ = downstream_write.send(Message::Close(None)).await;
                    break "shutdown";
                }
            }
            message = downstream_read.next() => {
                let Some(Ok(message)) = message else {
                    let _ = upstream_tx.send(Message::Close(None));
                    break "cli";
                };
                if let Some((metadata, text)) = log_frame(&state, CLI_TO_APP, &message) {
                    annotate_cli_response(&state, &metadata, &text);
                }
                let is_close = message.is_close();
                if upstream_tx.send(message).is_err() || is_close {
                    break "cli";
                }
            }
            message = upstream_read.next() => {
                let Some(Ok(message)) = message else {
                    let _ = downstream_write.send(Message::Close(None)).await;
                    break "app_server";
                };
                let is_close = message.is_close();
                let forward = handle_app_to_cli(&state, &message, &upstream_tx);
                if forward && downstream_write.send(message).await.is_err() {
                    break "app_server";
                }
                if is_close {
                    break "app_server";
                }
            }
        }
    };

    drop(upstream_tx);
    if time::timeout(WRITER_DRAIN_TIMEOUT, &mut writer_task)
        .await
        .is_err()
    {
        writer_task.abort();
    }
    reason
}

/// Logs a frame in full and returns its classified metadata plus raw text
/// when it was a text (JSON-RPC) message.
fn log_frame(
    state: &SharedState,
    direction: &str,
    message: &Message,
) -> Option<(JsonRpcMetadata, String)> {
    match message {
        Message::Text(text) => {
            let text = text.as_str().to_string();
            let metadata = classify_json_rpc(&text);
            let header = format!(
                "{direction} kind={:?} method={} id={}",
                metadata.kind,
                metadata.method.as_deref().unwrap_or("-"),
                metadata
                    .id
                    .as_ref()
                    .map(ToString::to_string)
                    .unwrap_or_else(|| "-".to_string())
            );
            state.logger.block(&header, &pretty_json_text(&text));
            Some((metadata, text))
        }
        Message::Binary(data) => {
            state
                .logger
                .line(&format!("{direction} kind=binary bytes={}", data.len()));
            None
        }
        Message::Ping(_) => {
            state.logger.line(&format!("{direction} kind=ping"));
            None
        }
        Message::Pong(_) => {
            state.logger.line(&format!("{direction} kind=pong"));
            None
        }
        Message::Close(frame) => {
            state
                .logger
                .line(&format!("{direction} kind=close frame={frame:?}"));
            None
        }
        Message::Frame(_) => {
            state.logger.line(&format!(
                "{direction} kind=raw-frame (unexpected outside read())"
            ));
            None
        }
    }
}

fn pretty_json_text(text: &str) -> String {
    match serde_json::from_str::<Value>(text) {
        Ok(value) => serde_json::to_string_pretty(&value).unwrap_or_else(|_| text.to_string()),
        Err(error) => format!("<non-JSON body, parse error: {error}>\n{text}"),
    }
}

fn pretty_value(value: &Value) -> String {
    serde_json::to_string_pretty(value).unwrap_or_else(|_| value.to_string())
}

/// Handles a frame flowing App Server -> CLI. Returns whether it should
/// still be forwarded down to the CLI.
fn handle_app_to_cli(
    state: &SharedState,
    message: &Message,
    upstream_tx: &mpsc::UnboundedSender<Message>,
) -> bool {
    let Some((metadata, text)) = log_frame(state, APP_TO_CLI, message) else {
        return true;
    };
    annotate_generic(state, APP_TO_CLI, &metadata);

    if metadata.kind != JsonRpcKind::Request
        || metadata.method.as_deref() != Some(REQUEST_APPROVAL_METHOD)
    {
        return true;
    }

    let Ok(full) = serde_json::from_str::<Value>(&text) else {
        state
            .logger
            .line("ERROR failed to parse requestApproval frame as JSON despite classification succeeding; passthrough");
        return true;
    };
    let Some(id) = full.get("id").cloned() else {
        state
            .logger
            .line("ERROR requestApproval frame has no id; cannot intervene, passthrough");
        return true;
    };
    let params = full.get("params").cloned().unwrap_or(Value::Null);
    log_request_approval_params(&state.logger, &params);

    let occurrence = state.approvals_detected.fetch_add(1, Ordering::SeqCst) + 1;
    state.logger.line(&format!(
        "requestApproval #{occurrence}/{} detected (id={id})",
        state.max_approvals
    ));

    let id_key = id.to_string();
    let turn_id = params
        .get("turnId")
        .and_then(Value::as_str)
        .map(str::to_string);
    let available: Vec<Value> = params
        .get("availableDecisions")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();

    let mut tracked = TrackedApproval::new(id.clone(), turn_id, state.logger.elapsed_ms());

    let forward_to_cli = match state.mode {
        Mode::Observe => {
            tracked.note = "observe: passthrough, no intervention".to_string();
            true
        }
        Mode::HoldForever => {
            tracked.note =
                "hold-forever: swallowed, never forwarded, no response scheduled".to_string();
            state.logger.line(
                "INTERVENE hold-forever: withholding requestApproval from CLI permanently \
                 (no response will ever be sent; watching for an App Server-side timeout)",
            );
            false
        }
        Mode::Race | Mode::Hold => {
            if available.is_empty() {
                state.logger.line(
                    "NOTE availableDecisions is empty/absent; cannot fabricate a response, \
                     passthrough without intervention",
                );
                tracked.note = "no availableDecisions offered; passthrough".to_string();
                true
            } else {
                match select_decision(&available, state.decision_arg.as_deref()) {
                    Ok(decision) => {
                        let decision = decision.clone();
                        tracked.decision = Some(decision.clone());
                        let forward = state.mode == Mode::Race;
                        if forward {
                            state.logger.line(&format!(
                                "INTERVENE race: forwarding requestApproval to CLI as usual, AND \
                                 scheduling a probe response with decision {} in {:?}",
                                decision_label(&decision),
                                state.delay
                            ));
                            tracked.note =
                                "race: forwarded to CLI + probe response scheduled".to_string();
                        } else {
                            state.logger.line(&format!(
                                "INTERVENE hold: withholding requestApproval from CLI, scheduling a \
                                 probe response with decision {} in {:?}",
                                decision_label(&decision),
                                state.delay
                            ));
                            tracked.note =
                                "hold: withheld from CLI + probe response scheduled".to_string();
                        }
                        schedule_probe_response(
                            state,
                            upstream_tx,
                            id.clone(),
                            id_key.clone(),
                            decision,
                        );
                        forward
                    }
                    Err(message) => {
                        state
                            .logger
                            .line(&format!("ERROR decision selection failed: {message}"));
                        tracked.note =
                            format!("decision mismatch ({message}); passthrough, no intervention");
                        true
                    }
                }
            }
        }
    };

    state
        .tracked
        .lock()
        .unwrap()
        .insert(id_key.clone(), tracked);
    schedule_settlement_watch(state, id_key);
    forward_to_cli
}

fn log_request_approval_params(logger: &Logger, params: &Value) {
    let command = params
        .get("command")
        .and_then(Value::as_str)
        .unwrap_or("<none>");
    let cwd = params
        .get("cwd")
        .and_then(Value::as_str)
        .unwrap_or("<none>");
    let reason = params
        .get("reason")
        .and_then(Value::as_str)
        .unwrap_or("<none>");
    let kind = params
        .get("kind")
        .and_then(Value::as_str)
        .unwrap_or("command");
    logger.line(&format!(
        "requestApproval fields: command={command:?} cwd={cwd:?} reason={reason:?} kind={kind:?}"
    ));
    let available = params
        .get("availableDecisions")
        .cloned()
        .unwrap_or(Value::Null);
    logger.block(
        "requestApproval availableDecisions",
        &pretty_value(&available),
    );
    logger.block("requestApproval params (full)", &pretty_value(params));
}

fn schedule_probe_response(
    state: &SharedState,
    upstream_tx: &mpsc::UnboundedSender<Message>,
    id: Value,
    id_key: String,
    decision: Value,
) {
    let state = state.clone();
    let upstream_tx = upstream_tx.clone();
    let delay = state.delay;
    tokio::spawn(async move {
        time::sleep(delay).await;
        let response = json!({
            "jsonrpc": "2.0",
            "id": id,
            "result": { "decision": decision },
        });
        let text = serde_json::to_string(&response).unwrap_or_default();
        state.logger.block(
            &format!("{PROBE_TO_APP} sending fabricated response for id={id}"),
            &pretty_json_text(&text),
        );
        if let Ok(mut tracked) = state.tracked.lock() {
            if let Some(entry) = tracked.get_mut(&id_key) {
                entry.probe_response_sent = true;
                entry.probe_response_at_ms = Some(state.logger.elapsed_ms());
            }
        }
        if upstream_tx.send(Message::text(text)).is_err() {
            state
                .logger
                .line("ERROR failed to send fabricated response upstream (channel closed)");
        }
    });
}

fn annotate_cli_response(state: &SharedState, metadata: &JsonRpcMetadata, text: &str) {
    if metadata.kind != JsonRpcKind::Response {
        return;
    }
    let Some(id) = metadata.id.as_ref() else {
        return;
    };
    let id_key = id.to_string();
    let body = serde_json::from_str::<Value>(text)
        .ok()
        .and_then(|full| full.get("result").or_else(|| full.get("error")).cloned());
    let mut tracked = state.tracked.lock().unwrap();
    if let Some(entry) = tracked.get_mut(&id_key) {
        entry.cli_response_seen = true;
        entry.cli_response_at_ms = Some(state.logger.elapsed_ms());
        entry.cli_response_body = body;
        let note = if entry.probe_response_sent {
            format!(
                "[correlate] this is the CLI's OWN response to requestApproval id={id}, arriving \
                 AFTER the probe already answered at +{}ms -- a duplicate submission to the App Server",
                entry.probe_response_at_ms.unwrap_or_default()
            )
        } else {
            format!(
                "[correlate] this is the CLI's own response to requestApproval id={id} (no probe \
                 response was sent for this id)"
            )
        };
        drop(tracked);
        state.logger.line(&note);
    }
}

fn annotate_generic(state: &SharedState, direction: &str, metadata: &JsonRpcMetadata) {
    let mut tracked = state.tracked.lock().unwrap();
    if tracked.is_empty() {
        return;
    }
    if metadata.method.as_deref() == Some("turn/completed") {
        if let Some(turn_id) = &metadata.turn_id {
            for entry in tracked.values_mut() {
                if entry.turn_id.as_deref() == Some(turn_id.as_str()) && !entry.turn_completed {
                    entry.turn_completed = true;
                    entry.turn_completed_at_ms = Some(state.logger.elapsed_ms());
                    entry.turn_status = metadata.turn_status.clone();
                    let id = entry.id.clone();
                    let status = entry.turn_status.clone();
                    drop(tracked);
                    state.logger.line(&format!(
                        "[correlate] {direction} turn/completed for turnId={turn_id} (approval \
                         id={id}, turn.status={})",
                        status.as_deref().unwrap_or("-")
                    ));
                    return;
                }
            }
        }
    } else if metadata.method.as_deref() == Some("serverRequest/resolved") {
        if let Some(request_id) = &metadata.request_id {
            let key = request_id.to_string();
            if let Some(entry) = tracked.get_mut(&key) {
                entry.resolved_notification_seen = true;
                entry.resolved_notification_at_ms = Some(state.logger.elapsed_ms());
                drop(tracked);
                state.logger.line(&format!(
                    "[correlate] {direction} serverRequest/resolved for id={request_id}"
                ));
            }
        }
    } else if metadata.response_is_error {
        if let Some(id) = &metadata.id {
            let key = id.to_string();
            if let Some(entry) = tracked.get_mut(&key) {
                entry.error_response_seen = true;
                entry.error_response_at_ms = Some(state.logger.elapsed_ms());
                drop(tracked);
                state.logger.line(&format!(
                    "[correlate] {direction} JSON-RPC error response for id={id}"
                ));
            }
        }
    }
}

/// Watches one requestApproval occurrence until it settles or the observe
/// window runs out, instead of ending the run on a fixed post-detection
/// timer.
///
/// This replaces an earlier design (`schedule_drain_shutdown`) that slept a
/// FIXED `--delay-seconds + 2s` after detecting the requestApproval and then
/// shut everything down. On a real device run with `--mode observe` (no
/// intervention at all, so the fixed timer was the only thing driving
/// shutdown), the probe exited about 7 seconds after the request appeared --
/// BEFORE the human at the keyboard had answered the CLI's prompt. That
/// timer was measuring the wrong thing: what `hold`/`race` actually need to
/// observe is what happens AFTER an answer is sent -- `serverRequest/resolved`,
/// the approved command actually running, `turn/completed`, and (for `race`)
/// a late/duplicate response from the CLI arriving at some unpredictable
/// human-paced time. A fixed timer anchored to detection has no way to know
/// any of that has happened yet, so it cuts the log off exactly where the
/// interesting part starts. Instead, this polls the tracked state for the
/// occurrence and only finalizes it once a response (the probe's own or the
/// CLI's) AND `turn/completed` have both been observed and stayed observed
/// for `SETTLE_TAIL` (nothing else about it is still in flight), or once
/// `--observe-seconds` has elapsed since detection with no such luck --
/// whichever happens first, so a configuration that never sends
/// `turn/completed` (or never gets answered at all, as in `hold-forever`)
/// still terminates in bounded time.
fn schedule_settlement_watch(state: &SharedState, id_key: String) {
    let state = state.clone();
    tokio::spawn(async move {
        let deadline = Instant::now() + state.observe_seconds;
        let mut settled_since: Option<Instant> = None;
        loop {
            let now = Instant::now();
            let (responded, turn_done, response_at_ms, turn_at_ms) = {
                let tracked = state.tracked.lock().unwrap();
                match tracked.get(&id_key) {
                    Some(entry) => (
                        entry.probe_response_sent || entry.cli_response_seen,
                        entry.turn_completed,
                        entry.probe_response_at_ms.or(entry.cli_response_at_ms),
                        entry.turn_completed_at_ms,
                    ),
                    None => (false, false, None, None),
                }
            };

            if responded && turn_done {
                let since = *settled_since.get_or_insert(now);
                if now.saturating_duration_since(since) >= SETTLE_TAIL {
                    finalize_occurrence(
                        &state,
                        &id_key,
                        SettlementOutcome::Settled,
                        format!(
                            "settled (response observed at +{}ms, turn/completed at +{}ms, \
                             tail {}s elapsed)",
                            response_at_ms.unwrap_or_default(),
                            turn_at_ms.unwrap_or_default(),
                            SETTLE_TAIL.as_secs()
                        ),
                    );
                    return;
                }
            } else {
                settled_since = None;
            }

            if now >= deadline {
                finalize_occurrence(
                    &state,
                    &id_key,
                    SettlementOutcome::TimedOut,
                    format!(
                        "observe window elapsed (--observe-seconds {}) — the approval may not \
                         have been resolved",
                        state.observe_seconds.as_secs()
                    ),
                );
                return;
            }

            let remaining = deadline.saturating_duration_since(now);
            time::sleep(
                SETTLE_POLL_INTERVAL
                    .min(remaining)
                    .max(Duration::from_millis(1)),
            )
            .await;
        }
    });
}

/// Marks one occurrence's observation window as finished, and -- once
/// `max_approvals` occurrences have each finished this way -- ends the run.
fn finalize_occurrence(
    state: &SharedState,
    id_key: &str,
    outcome: SettlementOutcome,
    reason_detail: String,
) {
    let already_finalized = {
        let mut tracked = state.tracked.lock().unwrap();
        match tracked.get_mut(id_key) {
            Some(entry) if entry.outcome.is_none() => {
                entry.outcome = Some(outcome);
                entry.outcome_at_ms = Some(state.logger.elapsed_ms());
                false
            }
            _ => true,
        }
    };
    if already_finalized {
        return;
    }
    state
        .logger
        .line(&format!("requestApproval id={id_key} {reason_detail}"));

    let processed = state.approvals_processed.fetch_add(1, Ordering::SeqCst) + 1;
    if processed >= state.max_approvals
        && !state.final_shutdown_triggered.swap(true, Ordering::SeqCst)
    {
        state
            .logger
            .line(&format!("shutdown reason: {reason_detail}"));
        if outcome == SettlementOutcome::TimedOut {
            state
                .final_shutdown_is_timeout
                .store(true, Ordering::SeqCst);
        }
        let _ = state.shutdown_tx.send(true);
    }
}

fn select_decision<'a>(
    available: &'a [Value],
    requested: Option<&str>,
) -> Result<&'a Value, String> {
    match requested {
        None => available
            .first()
            .ok_or_else(|| "availableDecisions is empty".to_string()),
        Some(name) => available
            .iter()
            .find(|candidate| decision_matches(candidate, name))
            .ok_or_else(|| {
                let choices: Vec<String> = available.iter().map(decision_label).collect();
                format!(
                    "requested decision {name:?} not found; available: [{}]",
                    choices.join(", ")
                )
            }),
    }
}

fn decision_matches(value: &Value, name: &str) -> bool {
    match value {
        Value::String(candidate) => candidate == name,
        Value::Object(map) if map.len() == 1 => map.keys().next().is_some_and(|key| key == name),
        _ => false,
    }
}

fn decision_label(value: &Value) -> String {
    match value {
        Value::String(candidate) => candidate.clone(),
        Value::Object(map) if map.len() == 1 => map
            .keys()
            .next()
            .cloned()
            .unwrap_or_else(|| "?".to_string()),
        other => other.to_string(),
    }
}

fn print_summary(
    logger: &Logger,
    tracked: &StdMutex<HashMap<String, TrackedApproval>>,
    timed_out: bool,
) {
    let tracked = tracked.lock().unwrap();
    logger.line(&format!(
        "=== SUMMARY: {} requestApproval occurrence(s) observed ===",
        tracked.len()
    ));
    let mut entries: Vec<&TrackedApproval> = tracked.values().collect();
    entries.sort_by_key(|entry| entry.detected_at_ms);
    for entry in entries {
        let header = format!("id={} (received at +{}ms)", entry.id, entry.detected_at_ms);
        let outcome = match entry.outcome {
            Some(SettlementOutcome::Settled) => "settled",
            Some(SettlementOutcome::TimedOut) => "observe-window-timeout",
            None => "unresolved (run ended before this occurrence's watch finished)",
        };
        let body = format!(
            "note: {}\n\
             observation outcome: {}{}\n\
             probe response: sent={} decision={}{}\n\
             CLI response: seen={}{} body={}\n\
             duplicate (both probe and CLI answered this id): {}\n\
             serverRequest/resolved observed: {}{}\n\
             turn/completed observed: {} turn.status={}{}\n\
             JSON-RPC error response observed for this id: {}{}",
            entry.note,
            outcome,
            optional_ms(entry.outcome_at_ms),
            entry.probe_response_sent,
            entry
                .decision
                .as_ref()
                .map(decision_label)
                .unwrap_or_else(|| "-".to_string()),
            optional_ms(entry.probe_response_at_ms),
            entry.cli_response_seen,
            optional_ms(entry.cli_response_at_ms),
            entry
                .cli_response_body
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_else(|| "-".to_string()),
            entry.probe_response_sent && entry.cli_response_seen,
            entry.resolved_notification_seen,
            optional_ms(entry.resolved_notification_at_ms),
            entry.turn_completed,
            entry.turn_status.as_deref().unwrap_or("-"),
            optional_ms(entry.turn_completed_at_ms),
            entry.error_response_seen,
            optional_ms(entry.error_response_at_ms),
        );
        logger.block(&header, &body);
    }
    if timed_out {
        logger
            .line("WARNING: exited on the observe-window timeout; the aftermath may be incomplete");
    }
    logger.line("=== END SUMMARY ===");
}

fn optional_ms(value: Option<u128>) -> String {
    match value {
        Some(ms) => format!(" (+{ms}ms)"),
        None => String::new(),
    }
}

struct Logger {
    file: StdMutex<File>,
    start: Instant,
}

impl Logger {
    fn create(path: &Path) -> Result<Self, String> {
        let file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(path)
            .map_err(|error| format!("failed to create log file {}: {error}", path.display()))?;
        Ok(Self {
            file: StdMutex::new(file),
            start: Instant::now(),
        })
    }

    fn elapsed_ms(&self) -> u128 {
        self.start.elapsed().as_millis()
    }

    fn emit(&self, ms: u128, text: &str) {
        let stamped = format!("[+{ms:>8}ms] {text}");
        println!("{stamped}");
        if let Ok(mut file) = self.file.lock() {
            let _ = writeln!(file, "{stamped}");
            let _ = file.flush();
        }
    }

    fn line(&self, text: &str) {
        self.emit(self.elapsed_ms(), text);
    }

    /// Logs a header line followed by every line of `body`, all indented and
    /// stamped with the same elapsed time so a multi-line frame stays
    /// visually grouped and time-ordered.
    fn block(&self, header: &str, body: &str) {
        let ms = self.elapsed_ms();
        self.emit(ms, header);
        for line in body.lines() {
            self.emit(ms, &format!("    {line}"));
        }
    }

    /// Writes text verbatim, with no timestamp prefix, to both the console
    /// and the log file. Used only for the copy-pasteable CLI launch
    /// instructions, which must not be corrupted by a log prefix.
    fn raw(&self, text: &str) {
        println!("{text}");
        if let Ok(mut file) = self.file.lock() {
            let _ = writeln!(file, "{text}");
            let _ = file.flush();
        }
    }
}

struct ChildKillGuard(Option<Child>);

impl ChildKillGuard {
    fn new(child: Child) -> Self {
        Self(Some(child))
    }

    fn as_mut(&mut self) -> &mut Child {
        self.0.as_mut().expect("child guard used after release")
    }

    fn into_inner(mut self) -> Child {
        self.0.take().expect("child guard used after release")
    }
}

impl Drop for ChildKillGuard {
    fn drop(&mut self) {
        if let Some(mut child) = self.0.take() {
            let _ = child.start_kill();
        }
    }
}

async fn wait_for_port(
    child: &mut Child,
    port: u16,
    timeout: Duration,
    logger: &Logger,
) -> Result<(), String> {
    let deadline = Instant::now() + timeout;
    loop {
        if let Some(exit) = child
            .try_wait()
            .map_err(|error| format!("failed to poll Codex App Server: {error}"))?
        {
            return Err(format!("Codex App Server exited before listening: {exit}"));
        }
        if TcpStream::connect(("127.0.0.1", port)).await.is_ok() {
            logger.line(&format!(
                "Codex App Server is listening on 127.0.0.1:{port}"
            ));
            return Ok(());
        }
        if Instant::now() >= deadline {
            return Err(format!(
                "timed out waiting for Codex App Server to listen on 127.0.0.1:{port}"
            ));
        }
        time::sleep(Duration::from_millis(150)).await;
    }
}

async fn pick_free_port() -> Result<u16, String> {
    let listener = TcpListener::bind("127.0.0.1:0")
        .await
        .map_err(|error| format!("failed to allocate a free port: {error}"))?;
    listener
        .local_addr()
        .map(|addr: SocketAddr| addr.port())
        .map_err(|error| format!("failed to read allocated port: {error}"))
}

fn random_token() -> Result<String, String> {
    let mut bytes = [0_u8; 32];
    getrandom::fill(&mut bytes).map_err(|error| format!("failed to generate token: {error}"))?;
    Ok(hex::encode(bytes))
}

fn constant_time_eq(left: &str, right: &str) -> bool {
    left.as_bytes().ct_eq(right.as_bytes()).into()
}

fn absolute_path(path: &Path) -> Result<PathBuf, String> {
    if path.is_absolute() {
        Ok(path.to_path_buf())
    } else {
        env::current_dir()
            .map(|cwd| cwd.join(path))
            .map_err(|error| format!("failed to resolve path {}: {error}", path.display()))
    }
}

/// Minimal Ctrl+C detection via a raw `SetConsoleCtrlHandler` binding.
///
/// `tokio`'s `signal` feature is not enabled for this workspace and adding
/// it (or the `windows` crate's `Win32_System_Console` feature) would be a
/// new dependency footprint, which this probe must avoid. `kernel32` is
/// always linked on Windows targets, so this needs no extra crate.
#[cfg(windows)]
mod ctrlc {
    use std::sync::atomic::AtomicBool;

    pub static SHUTDOWN_REQUESTED: AtomicBool = AtomicBool::new(false);

    const CTRL_C_EVENT: u32 = 0;
    const CTRL_BREAK_EVENT: u32 = 1;
    const CTRL_CLOSE_EVENT: u32 = 2;

    #[link(name = "kernel32")]
    extern "system" {
        fn SetConsoleCtrlHandler(
            handler_routine: Option<unsafe extern "system" fn(u32) -> i32>,
            add: i32,
        ) -> i32;
    }

    unsafe extern "system" fn handler(ctrl_type: u32) -> i32 {
        match ctrl_type {
            CTRL_C_EVENT | CTRL_BREAK_EVENT | CTRL_CLOSE_EVENT => {
                SHUTDOWN_REQUESTED.store(true, std::sync::atomic::Ordering::SeqCst);
                1
            }
            _ => 0,
        }
    }

    pub fn install() {
        // Safety: `handler` matches the expected `PHANDLER_ROUTINE` signature
        // and is valid for the lifetime of the process (it is a plain `fn`,
        // never unregistered).
        unsafe {
            let _ = SetConsoleCtrlHandler(Some(handler), 1);
        }
    }
}

#[cfg(not(windows))]
mod ctrlc {
    use std::sync::atomic::AtomicBool;

    pub static SHUTDOWN_REQUESTED: AtomicBool = AtomicBool::new(false);

    pub fn install() {}
}

#[cfg(windows)]
fn hide_child_window(command: &mut Command) {
    use std::os::windows::process::CommandExt;
    const CREATE_NO_WINDOW: u32 = 0x0800_0000;
    command.as_std_mut().creation_flags(CREATE_NO_WINDOW);
}

#[cfg(not(windows))]
fn hide_child_window(_command: &mut Command) {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[cfg(windows)]
    fn select_codex_executable_skips_extensionless_line_and_picks_cmd_shim() {
        // Reproduces the real `where.exe codex` output on a machine where
        // Codex is installed via npm: an extensionless shell-script line
        // first, then the runnable `.cmd` shim.
        let output = b"C:\\Users\\Onigiri\\AppData\\Roaming\\npm\\codex\r\n\
                        C:\\Users\\Onigiri\\AppData\\Roaming\\npm\\codex.cmd\r\n";
        let selected = select_codex_executable(output).expect("a runnable candidate");
        assert_eq!(
            selected,
            PathBuf::from(r"C:\Users\Onigiri\AppData\Roaming\npm\codex.cmd")
        );
    }

    #[test]
    #[cfg(windows)]
    fn select_codex_executable_returns_none_when_nothing_is_runnable() {
        let output = b"C:\\Users\\Onigiri\\AppData\\Roaming\\npm\\codex\r\n";
        assert!(select_codex_executable(output).is_none());
    }

    #[test]
    fn select_decision_defaults_to_first_when_unrequested() {
        let available = vec![json!("accept"), json!("decline")];
        let chosen = select_decision(&available, None).unwrap();
        assert_eq!(chosen, &json!("accept"));
    }

    #[test]
    fn select_decision_matches_string_variant_by_name() {
        let available = vec![json!("accept"), json!("decline"), json!("cancel")];
        let chosen = select_decision(&available, Some("decline")).unwrap();
        assert_eq!(chosen, &json!("decline"));
    }

    #[test]
    fn select_decision_matches_object_variant_by_its_single_key() {
        let available = vec![
            json!("accept"),
            json!({"acceptWithExecpolicyAmendment": {"execpolicy_amendment": ["foo"]}}),
        ];
        let chosen = select_decision(&available, Some("acceptWithExecpolicyAmendment")).unwrap();
        assert_eq!(
            chosen,
            &json!({"acceptWithExecpolicyAmendment": {"execpolicy_amendment": ["foo"]}})
        );
    }

    #[test]
    fn select_decision_reports_available_choices_on_mismatch() {
        let available = vec![json!("accept"), json!("decline")];
        let error = select_decision(&available, Some("nope")).unwrap_err();
        assert!(error.contains("accept"));
        assert!(error.contains("decline"));
    }

    #[test]
    fn select_decision_errors_on_empty_list() {
        let available: Vec<Value> = Vec::new();
        assert!(select_decision(&available, None).is_err());
    }

    #[test]
    fn constant_time_token_check_rejects_length_and_value_mismatches() {
        assert!(constant_time_eq("same", "same"));
        assert!(!constant_time_eq("same", "diff"));
        assert!(!constant_time_eq("same", "longer-value"));
    }

    #[test]
    fn build_response_wraps_decision_opaquely() {
        let response = json!({
            "jsonrpc": "2.0",
            "id": json!(7),
            "result": { "decision": json!("accept") },
        });
        assert_eq!(response["result"]["decision"], json!("accept"));
        assert_eq!(response["id"], json!(7));
    }

    #[test]
    fn mode_parses_all_documented_values() {
        assert_eq!(Mode::parse("observe").unwrap(), Mode::Observe);
        assert_eq!(Mode::parse("race").unwrap(), Mode::Race);
        assert_eq!(Mode::parse("hold").unwrap(), Mode::Hold);
        assert_eq!(Mode::parse("hold-forever").unwrap(), Mode::HoldForever);
        assert!(Mode::parse("bogus").is_err());
    }

    #[test]
    fn powershell_quote_escapes_embedded_single_quotes() {
        assert_eq!(powershell_quote("it's"), "'it''s'");
    }

    #[test]
    fn parse_args_defaults_observe_seconds_to_120_and_accepts_override() {
        let args = vec![OsString::from("--mode"), OsString::from("observe")];
        let options = parse_args(&args).unwrap();
        assert_eq!(options.observe_seconds, Duration::from_secs(120));

        let args = vec![
            OsString::from("--mode"),
            OsString::from("hold"),
            OsString::from("--observe-seconds"),
            OsString::from("30"),
        ];
        let options = parse_args(&args).unwrap();
        assert_eq!(options.observe_seconds, Duration::from_secs(30));
    }
}
